{{ range $dictionary := .Values.component.dictionaries }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if $.Values.annotations }}
  annotations:
    th2.exactpro.com/antecedent: {{ $.Values.annotations }}
  {{- end }}
  name: {{ $dictionary.name | lower }}-dictionary
  labels:
    app: {{ $dictionary.name }}
    type: dictionary
data: 
  {{ $dictionary.name }}-{{ $dictionary.type }}.encoded: |
    {{ $dictionary.data }}
{{ end }}
