{{/*
Generating configMap for k8
*/}}
{{- define "configMap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if .annotations }}
  annotations:
    th2.exactpro.com/antecedent: {{ .annotations }}
  {{- end }}
  name: {{ .component.name }}-app-config
  labels:
    app: {{ .component.name }}
data: 
  custom.json: |
    {{ .component.custom | toJson }}
  grpc.json: |
    {{ .component.grpcRouter | toJson }}
  mq.json: |
    {{ .component.routerMq | toJson }}
  {{- if .component.prometheus }}
  prometheus.json: |
    {{ .component.prometheus | toJson }}
  {{- end }}
  {{- if .component.extendedSettings.logFile }}
  log4j.properties: |
    {{ .component.extendedSettings.logFile | toJson }}
  {{- end }}
  box.json: |
    {"boxName":{{ .component.name | quote }}}
{{ end }}
