{{/* 
Generating deployment for k8
*/}}
{{- define "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .component.name }}
  name: {{ .component.name }}
  annotations:
    {{- if .annotations }}
    th2.exactpro.com/antecedent: {{ .annotations }}
    {{- end }}
spec:
  {{- if .component.extendedSettings.replicas }}      
  replicas: {{ .component.extendedSettings.replicas }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ .component.name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include "configMap" . | sha256sum }}
        {{- range $dict := .component.dictionaries }}
        checksum/{{ $dict.name | lower }}: {{ $dict.checksum }}
        {{- end }}
        {{- if .annotations }}
        th2.exactpro.com/antecedent : {{ .annotations }}
        {{- end }}
      labels:
        app: {{ .component.name }}
        {{- if not .component.prometheus }}
        monitoring-pod: "true"
        {{- else }}
        {{- if .component.prometheus.enabled }}
        monitoring-pod: "true"
        {{- end }}
        {{- end }}
    spec:
      containers:
      - image: {{ .component.image }}
        name: {{ .component.name }}
        {{- include "prometheus-deploy" . }}
        {{- include "resources" . }}
        env:
        {{- if .component.extendedSettings.envVariables }}
        {{- range $envName, $envValue := .component.extendedSettings.envVariables }}
        - name: {{ $envName }}
          value: {{ $envValue | quote }}
        {{- end }}
        {{- end }}
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .component.secrets.rabbitMQ }}
              key: rabbitmq-password
        - name: CASSANDRA_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .component.secrets.cassandra }}
              key: cassandra-password
        {{- include "volumes" . }}        
      imagePullSecrets:
      - name: th2-solution
      - name: th2-core
      - name: th2-proprietary
      {{- if .component.extendedSettings.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirst
      {{- end }}
  revisionHistoryLimit: 2
{{- end }}
