{{/* 
Generating deployment for k8
*/}}
{{- define "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .component.name }}
  name: {{ .component.name }}
  annotations:
    {{- if .annotations }}
    th2.exactpro.com/antecedent: {{ .annotations }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .component.name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "configMap" . | sha256sum }}
        {{- range $dict := .component.dictionaries }}
        checksum/{{ $dict.name }}: {{ include "dictionary-configMap" (list $ $dict) | sha256sum }}
        {{- end }}
        {{- if .annotations }}
        th2.exactpro.com/antecedent : {{ .annotations }}
        {{- end }}
      labels:
        app: {{ .component.name }}
        {{- if not .component.prometheus }}
        monitoring-pod: "true"
        {{- else }}
        {{- if eq .component.prometheus.enabled "true" }}
        monitoring-pod: "true"
        {{- end }}
        {{- end }}
    spec:
      containers:
      - image: {{ .component.image }}
        name: {{ .component.name }}
        {{- include "prometheus-deploy" . }}
        {{- include "resources" . }}
        env:
        {{- if .component.extendedSettings.envVariables }}
        {{- range $envName, $envValue := .component.extendedSettings.envVariables }}
        - name: {{ $envName }}
          value: {{ $envValue | quote }}
        {{- end }}
        {{- end }}
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .component.secrets.rabbitMQ }}
              key: rabbitmq-password
        - name: CASSANDRA_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .component.secrets.cassandra }}
              key: cassandra-password
        volumeMounts:
{{- /* Old location for log4j.properties file. Will be removed further versions */}}
        - name: logging-volume
          mountPath: /home/etc/log4j.properties
          subPath: log4j.properties
{{- /* end old location */}}
        - name: configs
          mountPath: /var/th2/config/
        {{- range $volume := .component.extendedSettings.mounting }}
        - name: {{ $volume.pvcName | lower }}
          mountPath: {{ $volume.path | quote }}
        {{- end }}
      volumes:
      {{- range $volume := .component.extendedSettings.mounting }}
      - name: {{ $volume.pvcName | lower }}
        persistentVolumeClaim:
          claimName: {{ $volume.pvcName }}
      {{- end }}
{{- /* Old configmap name for log4j.properties file. Will be removed further versions */}}
      - name: logging-volume
        configMap:
          name: java-logging-config
{{- /* end old configmap name */}}
      - name: configs
        projected:
          sources:
          {{- if .component.extendedSettings.hostNetwork }}
          - configMap:
              name: rabbit-mq-external-app-config
          - configMap:
              name: cradle-external
          {{ else }}
          - configMap:
              name: rabbit-mq-app-config
          - configMap:
              name: cradle
          {{- end }}
          - configMap:
              name: {{ .component.name }}-app-config
          {{- range $dictionary := .component.dictionaries }}
          - configMap:
              name: {{ $.component.name }}-{{ $dictionary.name | lower }}-dictionary
          {{- end }}
      imagePullSecrets:
      - name: th2-solution
      - name: th2-core
      - name: th2-proprietary
      {{- if .component.extendedSettings.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirst
      {{- end }}
  revisionHistoryLimit: 2
{{- end }}
